AWSTemplateFormatVersion: 2010-09-09
Description: aUdacity - The template deploys a VPC
Resources:
  myUdacityVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: "true"
